version: "3.8"

services:

  postgres:
    image: postgres:14.2-alpine
    hostname: db
    container_name: solid_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solid
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
